/*
 * WMSProgessPanel.java
 *
 * Created on October 26, 2005, 12:55 PM
 */

package com.wms.util.gui.progress;

import java.awt.Dimension;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author  mstemen
 */
public class WMSProgressPanel extends javax.swing.JPanel {
    
    private Timer timer;
    private WMSJob job;
    private int jobCheckInterval = 1000;
    private boolean jobSet = false;
    private int defHeight = 480;
    private int defWidth = 640;
    private String version = System.getProperty("java.vm.version");
    private String jreName = System.getProperty("java.vm.name");
    // create a timer
    
    /** Creates new form WMSProgessPanel */
    public WMSProgressPanel( int min, int max ) {
        initComponents();
        Dimension defDim = new Dimension(defHeight, defWidth);
        this.setSize( defDim );
        progressMessage.setText( "Starting to Monitor Start-up" );
        progressNote.setText( "Init Progress System..." );
        jobProgressBar.setMinimum( min );
        jobProgressBar.setMaximum( max );      
        progJavaVersion.setText( jreName + " " + version );
        
    }
    
    public void start()
    {
        if( ! jobSet )
            return;
        
        timer = new Timer( jobCheckInterval, new ActionListener()
        
        {
           public void actionPerformed( ActionEvent e )
           {
               jobProgressBar.setValue( job.getCurrent() );
               progressNote.setText( job.getNote());
               if( job.isDone())
               {
                   timer.stop();
                   jobProgressBar.setValue( jobProgressBar.getMinimum() );
               }
               validate();
           }
        });
        timer.setInitialDelay( 0 );
        timer.start();
        
    }
    
    public void stop()
    {
        if( timer != null )
            timer.stop();       
    }
            
    public void setJob( WMSJob job )
    {
        this.job = job;
        job.setPanel( this );
        progressMessage.setText( job.getMessage() );
        jobSet = true;
    }
    
    public void setNote( String note )
    {
        progressNote.setText( note );
        validate();
    }
    
    public void setMessage( String message )
    {
        progressMessage.setText( message );        
        validate();
    }
    
    @Override
    public void validate()
    {
        jobProgressBar.validate();
        progressMessage.validate();
        progressNote.validate();
        jobProgressBar.repaint();
        super.validate();                        
        repaint();        

    }
    
    public void setMinimum( int min )
    {
        jobProgressBar.setMinimum( min );
    }
    
    public void setMaximum( int max )
    {
        jobProgressBar.setMaximum( max );
    }
    
    public void showLogo( boolean flag )
    {
        wmsProductLogo.setVisible( flag );
    }
    public void showVersion( boolean flag )
    {
        progJavaVersion.setVisible( flag );
    }
    
    public void setValue( int value )
    {
        // if( ParallaxMgr.getMgr() != null )
        //    ParallaxMgr.getMgr().getLog().write( "Setting done value to: " + value );
        jobProgressBar.setValue( value );
        validate();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        afSplashInfoPanel = new javax.swing.JPanel();
        wmsProductLogo = new javax.swing.JLabel();
        jobProgressBar = new javax.swing.JProgressBar();
        progressMessage = new javax.swing.JLabel();
        progressNote = new javax.swing.JLabel();
        javaVerLabel = new javax.swing.JLabel();
        progJavaVersion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        bgSplashPanel = new javax.swing.JPanel();
        afSplashBgImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new java.awt.GridLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(640, 480));
        jLayeredPane1.setOpaque(true);

        afSplashInfoPanel.setBackground(new java.awt.Color(204, 255, 255));
        afSplashInfoPanel.setMinimumSize(new java.awt.Dimension(550, 225));
        afSplashInfoPanel.setOpaque(false);
        afSplashInfoPanel.setPreferredSize(new java.awt.Dimension(550, 225));

        jobProgressBar.setStringPainted(true);

        progressMessage.setBackground(new java.awt.Color(0, 0, 0));
        progressMessage.setForeground(new java.awt.Color(0, 204, 204));

        progressNote.setBackground(new java.awt.Color(0, 0, 0));
        progressNote.setForeground(new java.awt.Color(0, 204, 204));

        javaVerLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        javaVerLabel.setForeground(new java.awt.Color(0, 51, 153));
        javaVerLabel.setText("Java Version: ");

        progJavaVersion.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        progJavaVersion.setForeground(new java.awt.Color(0, 51, 153));

        jTextPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jTextPane1.setText("The Anti-Frieze suite (SMS) is \"free\" to test and try.\nIf you wish to use it to actually run your shop--Please donate what you think\nAnti - Frieze is worth to you\n\n\nCopyright © 2009 Wintermute Studio - All Rights Reserved.");
        jScrollPane1.setViewportView(jTextPane1);

        org.jdesktop.layout.GroupLayout afSplashInfoPanelLayout = new org.jdesktop.layout.GroupLayout(afSplashInfoPanel);
        afSplashInfoPanel.setLayout(afSplashInfoPanelLayout);
        afSplashInfoPanelLayout.setHorizontalGroup(
            afSplashInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(afSplashInfoPanelLayout.createSequentialGroup()
                .add(afSplashInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(afSplashInfoPanelLayout.createSequentialGroup()
                        .add(212, 212, 212)
                        .add(jobProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(afSplashInfoPanelLayout.createSequentialGroup()
                        .add(139, 139, 139)
                        .add(afSplashInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(progressMessage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 316, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(wmsProductLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 306, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(afSplashInfoPanelLayout.createSequentialGroup()
                        .add(118, 118, 118)
                        .add(progressNote, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 355, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(afSplashInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(javaVerLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(progJavaVersion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 188, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, afSplashInfoPanelLayout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 273, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        afSplashInfoPanelLayout.setVerticalGroup(
            afSplashInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, afSplashInfoPanelLayout.createSequentialGroup()
                .add(wmsProductLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(progressMessage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jobProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(progressNote, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(afSplashInfoPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(afSplashInfoPanelLayout.createSequentialGroup()
                        .add(210, 210, 210)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(15, 15, 15)
                        .add(javaVerLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, progJavaVersion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22))
        );

        afSplashInfoPanel.setBounds(10, 10, 620, 400);
        jLayeredPane1.add(afSplashInfoPanel, javax.swing.JLayeredPane.DRAG_LAYER);

        bgSplashPanel.setLayout(new java.awt.GridLayout(1, 0));

        afSplashBgImage.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        afSplashBgImage.setIcon(new javax.swing.ImageIcon("G:\\dev\\java\\Projects\\AntiFrieze\\src\\com\\wms\\antifrieze\\gui\\resources\\main_graphics\\AntiFriezeSplash_2 .jpg")); // NOI18N
        afSplashBgImage.setAlignmentY(0.0F);
        bgSplashPanel.add(afSplashBgImage);

        bgSplashPanel.setBounds(0, 0, 640, 480);
        jLayeredPane1.add(bgSplashPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel afSplashBgImage;
    public javax.swing.JPanel afSplashInfoPanel;
    public javax.swing.JPanel bgSplashPanel;
    public javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextPane jTextPane1;
    public javax.swing.JLabel javaVerLabel;
    public javax.swing.JProgressBar jobProgressBar;
    public javax.swing.JLabel progJavaVersion;
    public javax.swing.JLabel progressMessage;
    public javax.swing.JLabel progressNote;
    public javax.swing.JLabel wmsProductLogo;
    // End of variables declaration//GEN-END:variables
    
}
